# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.8
      - image: circleci/postgres:11.5
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install wagtail
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install coverage
            coverage run ./runtests.py
            coverage report
            coverage xml
            bash <(curl -s https://codecov.io/bash) -t "YOUR CODECOV TOKEN"
